# Site wide configuration

title:            Stuart Hinson
locale:           en_US
url:              https://stuarth.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Stuart Hinson
  avatar: stu.jpg
  bio: "Clojure programmer"
  email: 
  disqus-shortname: 
  twitter: lambdastu
  facebook: #username
  google:
    plus: #username
    analytics: UA-9797292-10
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: stuarth
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
